### ISSUE TITLE
Polish- use SnackBars with error message? form validation for log in and register like what happens if the user enters wrong password, -Vivian

### ISSUE THREAD

**Issue by meganm672** [meganm672/Block35-Capstone-Whisker-World#187]
use Snackbars?
the current snack bar on the log in and register shouldn't appear if the user enters the wrong password or incorrect character limits ... right now it does no matter if the password is correct or the form is empty

bcrypt compare - line 126 in index.js of auth

**Comment by vivianwong905** [comment]
https://github.com/meganm672/Block35-Capstone-Whisker-World/pull/191
